### PR TITLE
Adds iOS hotspot interfaces support

### PR DESCRIPTION
**Pull request by rshev**
This PR adds hotspot (bridge) interfaces to be recognised alongside WiFi interfaces.
Handy to be used when tethering from iPhone to iPads (with autoconfigure pac).

### CODE REVIEW

**Comment by rickyzhang82** [comment]
I'm not sure your use case. Are you saying you share your LTE network from your iPad? 

But if you iPad can work as hotspot, why do you need Tethering app?

**Comment by MrVas** [comment]
I could see an example where some carriers bill tethering from a device (iPad) at a different rate (tariff) than data usage on the actual device.

**Comment by rshev** [comment]
That's exactly what @MrVas is saying:
- I'm currently on holiday and here tethering is costing additional money, and quickly gets blocked after initial use with a warning
- hotspot is still available on the iPhone

**Comment by rickyzhang82** [comment]
@rshev I'm confused by what you said "hotspot is still available on the iPhone". I thought you runs the Tethering App on iPad. I bet I may misunderstand your use case. You may still use iPhone to run the Tethering App, is that correct?

In US, I can't even turn on hotspot feature on iOS device. That's the intention of this App.

Your PR uses the hotspot IP address of the iOS devices as the Tethering App service IP. In this case, your iOS device can live without the Tethering App. So why bother? Please convince this to me.

The Tethering App can **NOT** solve the problem that the carrier blocks your connection. Because your non-encrypted connection like http and etc can be easily filtered. It sounds like VPN is your solution but not this PR.

**Comment by rshev** [comment]
I am currently in Ukraine, and there is a similar problem in many neighbouring countries. You can have unlimited/vast amount of traffic available on your tariff, and hotspot option available on iPhone. But carriers here require you to pay extra for tethering. It works like that: you connect a device to your iPhone hotspot and soon receive a text saying "please pay for hotspot feature". The carriers allegedly detect a device with different TTL used on the same connection and block it for the session, i.e. the hotspot connection still getting established but no internet access through it. 

Having this change in place, my current setup is:
- I enable personal hotspot on iPhone
- run tethering app, start a proxy
- connect my WiFi-only iPad to the iPhone hotspot
- specify PAC proxy auto configuration on iPad (the phone's IP address will never change, which is quite handy)
- this way tethering works, as the carriers have no way to distinguish traffic coming from iPhone through proxy as they did with other devices

Also this change is not breaking any current IP address detection, as you can't have WiFi and hotspot connected at the same time. I believe there is a strong use case, contributing to the versatility of the app in general.

**Comment by rickyzhang82** [comment]
Thanks for your explanation in detail.

Detecting local wireless IP on iOS is an essential part in this App. If anything goes wrong in this method, it will break socks proxy server, DNS server and HTTP PAC file server binding to the correct IP address. The network interface `bridge\d+` and `en\d+` can coexist in Mac OS X. It is debatable to rule out the possibility that they can't coexist in future iOS or any other scenarios we can't foresee now.

I have tested your PR without hotspot enabled. It didn’t break mine. I have no way to test hotspot case. 

But I’d accept your PR only if you make the following changes in your PR:

1. Separate check on `bridge\d+` and `en\d+`. Make Line 31 - Line 48 as a function and reuse it for two interfaces check.
1. The wifi interface `en\d+` takes precedence over the hotspot interface `bridge\d+` so that if both interfaces exist, only use the wifi interface. 

I’m a conservative. Things have been working for 6 years. I don’t want to break it for a new feature that existing users don’t use. Also, I have no way to test it.

PS: I think you are using the Tether App to bypass the TTL check. But anyone can easily change TTL of client side like Mac OS X and Linux. So it is suspicious that this is the only mean carriers can use. The safest way is to use VPN on iOS with this App.

**Comment by MrVas** [comment]
Most major carriers in the US (AT&T, Sprint, TMO, and VZW) allow for tethering from an iOS device, but you will need to subscribe to the service, be billed at a higher rate, and usually have less data to use, then if you simply use data on your device. This vary greatly between carries and subscription plans.

I love this app for the ability to provide quick access to non-cellular connected devices. Having the ability to use it without a need for an additional WiFi access point, like a USB powered ESP8266, would be a huge plus.

**Comment by rickyzhang82** [comment]
@MrVas I don't want to hijack this PR.  I kept my grandfather unlimited data plan for almost a decade. The bill for data plan jumped from $35, $40 and now $45 a month. But I'm still not allowed to turn on hotspot feature. I assumed you are in US. How can you turn on Hotspot feature without Jailbreak?

**Comment by MrVas** [comment]
Most carries offer it, but you will have to subscribe to it. It's under Settings, Personal Hotstop (right below Cellular). If your carrier/plan does not offer/support it, then you will not see this option.

     On Saturday, June 29, 2019, 10:10:22 AM PDT, Ricky Zhang <notifications@github.com> wrote:  
 
 
@MrVas I don't want to hijack this PR. I kept my grandfather unlimited data plan for almost a decade. The bill for data plan jumped from $35, $40 and now $45 a month. But I'm still not allowed to turn on hotspot feature. I assumed you are in US. How can you turn on Hotspot feature without Jailbreak?

**Comment by rshev** [comment]
@rickyzhang82 I addressed your request to have proper wifi>hotspot precedence.

**Comment by rickyzhang82** [comment]
@rshev Thanks for your PR. I have squashed your PR branch and merged to master.

**Pull request closed without merging**
