### PR TITLE
Unlimited backgrounding

### PR DESCRIPTION
**Pull request by bsuh**
Adds [unlimited backgrounding](http://yifan.lu/2013/12/17/unlimited-backgrounding-on-ios/), to allow using switching to other apps on iPhone or turning off iPhone screen.

### CODE REVIEW

**Comment by rickyzhang82** [comment]
It is not clear to me that between two scenarios. Which one drain less power than another:
1. Set the screen light to the lowest level.
2. Play a silent song in background.

Do you find any differences?

**Comment by bsuh** [comment]
This only plays silent song in background for 1 second when you start tethering.

```
[[self player] setActionAtItemEnd:AVPlayerActionAtItemEndNone];
```

> Here’s the trick; this makes sure that the audio player is kept active after playing your sound file. The alternative is to keep looping a silent track, but why waste more CPU cycles (and battery)?

**Comment by jaderfeijo** [comment]
@rickyzhang82 I would suggest that this is not just a matter of battery saving, but also about the ability to use the phone while the tethering is enabled. With this "hack", the user can send the app to the background and keep using the phone normally without affecting the proxy server or bringing it down. I think for that "feature" alone, it would be worth merging.

**Comment by rickyzhang82** [comment]
I tested it on my iPhone for half an hour. It works like a charm.

Thanks for your fix @bsuh

**Comment by jaderfeijo** [comment]
Sweet!!!

@rickyzhang82 thank you for merging this :)

**Pull request closed without merging**
