### PR TITLE
Added support for all iOS device sizes & slightly prettier interface

### PR DESCRIPTION
**Pull request by rickybloomfield**
Converted icons to use Asset Catalog
Added Launch Screen file and removed default images
Added support for iPhone 6/6 Plus sizes, iPad Pro, and iPad split screen
Updated version number to 1.7
Switched name of project to 'Tethering' since that's what we're calling
it
Updated TableView class to use modern paradigms
Updated the storyboard to use UINavigationController and modern
paradigms (can more easily add functionality now)
Updated interface to "flat" to align with newer versions of iOS
Added button to open the GitHub wiki for additional configuration
information if needed

### CODE REVIEW

**Comment by TomK9er** [comment]
Great work, I love the app!

Has anyone tried this on iOS 10?

**Comment by rickyzhang82** [comment]
thanks for your great work @rickybloomfield ! I will test it ASAP.

**Comment by rickyzhang82** [comment]
@rickybloomfield 
Several things needs to be addressed:

- on iPhone, app icon is missing.
- remove redundant files/code:
   - remove SOCKS.xcodeproj/ if it is not used
   - remove commented out code

**Comment by rickybloomfield** [comment]
Thanks. Which version of iPhone did you test on? I included all icon versions in the app icon Assets file. I'll clean up some of the other things - I meant to take that out after testing and forgot.

**Comment by rickyzhang82** [comment]
iPhone 5S. I built it with Tethering.xcodepro.

**Comment by rickybloomfield** [comment]
Ok, all these issues should be fixed now. Thanks!

**Pull request merged**
