### PR TITLE
Added support for all iOS device sizes & slightly prettier interface

### PR DESCRIPTION
**Pull request by rickybloomfield**
Converted icons to use Asset Catalog
Added Launch Screen file and removed default images
Added support for iPhone 6/6 Plus sizes, iPad Pro, and iPad split screen
Updated version number to 1.7
Switched name of project to 'Tethering' since that's what we're calling it
Updated TableView class to use modern paradigms
Updated the storyboard to use UINavigationController and modern paradigms (can more easily add functionality now)
Updated interface to "flat" to align with newer versions of iOS
Added button to open the GitHub wiki for additional configuration information if needed

### CODE REVIEW

**Comment by rickyzhang82** [comment]
Could you take a snapshot of new UI change? TIA

**Comment by rickybloomfield** [comment]
Here you go. This expands to all iOS device sizes and also supports iPad split screen.

img_4700
img_4701

**Comment by rickybloomfield** [comment]
And tapping the "i" in the upper-right corner opens to the GitHub Wiki page.

**Comment by rickyzhang82** [comment]
It looks great in iPad. How about iPhone?

Could you mind fixing conflict and send a pull request again?

**Comment by rickybloomfield** [comment]
Those screenshots were actually both iPhone 6 Plus (it's big!). Below are screenshots from iPhone 5s and iPad Air 2 (in split screen mode).

Also, I've added the backgrounding code to mine. Resolving is going to be near impossible because of the changes to the project file, but if you accept everything here it should all work. Thanks.

simulator screen shot aug 13 2016 10 44 17 am
simulator screen shot aug 13 2016 10 45 42 am

**Comment by rickyzhang82** [comment]
If you can't fix the conflicts, I can't merge it.

**Pull request closed without merging**
